name: Release VSIX

on:
  push:
    branches:
      - master
  workflow_dispatch: # Allows manual execution of the workflow

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '21.2.0'

    - name: Install dependencies
      run: npm install

    - name: Install jq
      run: sudo apt-get install -y jq

    - name: Clean working directory
      run: git reset --hard HEAD

    - name: Bump version and update changelog
      id: bump_version
      env:
        TOKEN_FOR_WORKFLOW: ${{ secrets.TOKEN_FOR_WORKFLOW }}
      run: |
        git config --global user.name "balakrishna-maduru"
        git config --global user.email "balakrishnamaduru@gmail.com"
        git remote set-url origin https://balakrishna-maduru:${{ secrets.TOKEN_FOR_WORKFLOW }}@github.com/balakrishna-maduru/jenkins_vyavastaha.git
        CURRENT_VERSION=$(jq -r '.version' package.json)
        NEW_VERSION=$(npm version patch | sed 's/v//')
        echo "CURRENT_VERSION : $CURRENT_VERSION --> NEW_VERSION : $NEW_VERSION"
        while git rev-parse "v$NEW_VERSION" >/dev/null 2>&1; do
          echo "Tag v$NEW_VERSION already exists, bumping version again..."
          NEW_VERSION=$(echo $NEW_VERSION | awk -F. '{printf "%d.%d.%d", $1, $2, $3+1}')
          echo "Trying NEW_VERSION : $NEW_VERSION"
        done
        jq --arg version "$NEW_VERSION" '.version = $version' package.json > tmp.json && mv tmp.json package.json
        git add package.json
        git commit -m "Bump version to $NEW_VERSION"
        git tag -a "v$NEW_VERSION" -m "Release v$NEW_VERSION"
        git push origin master --tags
        echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

    - name: Install vsce
      run: npm install -g vsce

    - name: Package Extension
      run: vsce package

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        TOKEN_FOR_WORKFLOW: ${{ secrets.TOKEN_FOR_WORKFLOW }}
      with:
        tag_name: v${{ env.NEW_VERSION }}
        release_name: Release v${{ env.NEW_VERSION }}
        body: |
          ## Changes in this release
          - Describe your changes here

    - name: Upload VSIX to Release
      uses: actions/upload-release-asset@v1
      env:
        TOKEN_FOR_WORKFLOW: ${{ secrets.TOKEN_FOR_WORKFLOW }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./*.vsix
        asset_name: jenkins-vyavastaha-v${{ env.NEW_VERSION }}.vsix
        asset_content_type: application/octet-stream

    - name: Publish to Visual Studio Marketplace
      run: vsce publish -p ${{ secrets.VSCODE_MARKETPLACE_TOKEN }}
      env:
        VSCODE_MARKETPLACE_TOKEN: ${{ secrets.VSCODE_MARKETPLACE_TOKEN }}